import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ─── Helper ─────────────────────────────────────────────────────────────────

function rupees(amount) {
  if (amount == null) return 'Rs. 0.00'
  return 'Rs. ' + parseFloat(amount).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  })
}

function hrs(val) {
  if (val == null) return '0 hrs'
  return parseFloat(val).toFixed(1) + ' hrs'
}

// ─── Company Payroll Summary PDF (HR) ───────────────────────────────────────

export function generatePayrollPDF(payrollData, monthYear, companyName) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header bar
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, pageW, 22, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PayStride', 14, 14)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Payroll Management System', 14, 20)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('PAYROLL SUMMARY REPORT', pageW - 14, 11, { align: 'right' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Month: ${monthYear}`, pageW - 14, 17, { align: 'right' })

  // Company + meta info
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(companyName || 'Company', 14, 32)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`, 14, 38)
  doc.text(`Total workers: ${payrollData.length}`, 14, 43)

  // Summary totals
  const totalGross = payrollData.reduce((s, r) => s + parseFloat(r.grossPay || 0), 0)
  const totalPF    = payrollData.reduce((s, r) => s + parseFloat(r.pfDeduction || 0), 0)
  const totalESI   = payrollData.reduce((s, r) => s + parseFloat(r.esiDeduction || 0), 0)
  const totalNet   = payrollData.reduce((s, r) => s + parseFloat(r.netPay || 0), 0)

  const summaryX = pageW - 14
  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text(`Total Gross: ${rupees(totalGross)}`, summaryX, 32, { align: 'right' })
  doc.text(`Total PF: ${rupees(totalPF)}`, summaryX, 37, { align: 'right' })
  doc.text(`Total ESI: ${rupees(totalESI)}`, summaryX, 42, { align: 'right' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(5, 150, 105)
  doc.text(`Net Payable: ${rupees(totalNet)}`, summaryX, 48, { align: 'right' })

  // Divider
  doc.setDrawColor(200, 200, 200)
  doc.line(14, 51, pageW - 14, 51)

  // Table
  autoTable(doc, {
    startY: 55,
    head: [[
      'Worker', 'Department', 'Total Hrs', 'Regular', 'Overtime',
      'Gross Pay', 'PF (12%)', 'ESI (0.75%)', 'Net Pay'
    ]],
    body: payrollData.map(r => [
      r.workerName || '—',
      r.department || '—',
      hrs(r.totalHours),
      hrs(r.regularHours),
      parseFloat(r.overtimeHours || 0) > 0 ? hrs(r.overtimeHours) : '—',
      rupees(r.grossPay),
      rupees(r.pfDeduction),
      rupees(r.esiDeduction),
      rupees(r.netPay),
    ]),
    foot: [[
      `Total (${payrollData.length} workers)`, '',
      hrs(payrollData.reduce((s, r) => s + parseFloat(r.totalHours || 0), 0)),
      hrs(payrollData.reduce((s, r) => s + parseFloat(r.regularHours || 0), 0)),
      hrs(payrollData.reduce((s, r) => s + parseFloat(r.overtimeHours || 0), 0)),
      rupees(totalGross),
      rupees(totalPF),
      rupees(totalESI),
      rupees(totalNet),
    ]],
    headStyles: {
      fillColor: [30, 64, 175],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 3,
    },
    bodyStyles: { fontSize: 8, cellPadding: 3 },
    footStyles: {
      fillColor: [240, 253, 244],
      textColor: [6, 95, 70],
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 3,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 38 },
      5: { halign: 'right' },
      6: { halign: 'right', textColor: [220, 38, 38] },
      7: { halign: 'right', textColor: [220, 38, 38] },
      8: { halign: 'right', fontStyle: 'bold', textColor: [5, 150, 105] },
    },
    margin: { left: 14, right: 14 },
  })

  // Footer
  const finalY = doc.lastAutoTable.finalY + 8
  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'PF = 12% of gross wages  |  ESI = 0.75% of gross wages  |  Net = Gross - PF - ESI  |  Generated by PayStride',
    pageW / 2, finalY, { align: 'center' }
  )

  doc.save(`PayStride_Payroll_${monthYear}.pdf`)
}

// ─── Single Worker Payslip PDF (Worker) ─────────────────────────────────────

export function generatePayslipPDF(payslip, workerName, workerCode, companyName) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header bar
  doc.setFillColor(5, 150, 105)
  doc.rect(0, 0, pageW, 24, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('PayStride', 14, 13)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Worker Payroll Management', 14, 20)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('SALARY SLIP', pageW - 14, 12, { align: 'right' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Month: ${payslip.monthYear}`, pageW - 14, 19, { align: 'right' })

  // Worker info box
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(14, 30, pageW - 28, 28, 3, 3, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.roundedRect(14, 30, pageW - 28, 28, 3, 3, 'S')

  doc.setTextColor(30, 30, 30)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(workerName || '—', 20, 40)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Worker ID: ${workerCode || '—'}`, 20, 47)
  doc.text(`Company: ${companyName || '—'}`, 20, 53)

  doc.setFontSize(9)
  doc.setTextColor(100, 100, 100)
  doc.text(`Pay Period: ${payslip.monthYear}`, pageW - 20, 40, { align: 'right' })
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, pageW - 20, 47, { align: 'right' })

  // Attendance section
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('ATTENDANCE DETAILS', 14, 68)

  doc.setDrawColor(30, 64, 175)
  doc.setLineWidth(0.5)
  doc.line(14, 70, 90, 70)

  autoTable(doc, {
    startY: 73,
    head: [['Description', 'Hours']],
    body: [
      ['Total hours worked', hrs(payslip.totalHours)],
      ['Regular hours (up to 8/day)', hrs(payslip.regularHours)],
      ['Overtime hours (beyond 8/day)', hrs(payslip.overtimeHours)],
    ],
    headStyles: { fillColor: [30, 64, 175], textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 14, right: 14 },
    tableWidth: 'wrap',
  })

  // Earnings section
  const earningsY = doc.lastAutoTable.finalY + 10
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text('EARNINGS & DEDUCTIONS', 14, earningsY)

  doc.setDrawColor(5, 150, 105)
  doc.line(14, earningsY + 2, 90, earningsY + 2)

  const regularPay = parseFloat(payslip.grossPay || 0) - 
    (parseFloat(payslip.overtimeHours || 0) * (parseFloat(payslip.grossPay || 0) / 
    (parseFloat(payslip.totalHours || 1))) * 0.5)

  autoTable(doc, {
    startY: earningsY + 5,
    head: [['Description', 'Amount']],
    body: [
      ['Gross pay (regular + overtime × 1.5)', rupees(payslip.grossPay)],
      ['PF deduction (12% of gross)', '- ' + rupees(payslip.pfDeduction)],
      ['ESI deduction (0.75% of gross)', '- ' + rupees(payslip.esiDeduction)],
    ],
    foot: [['NET PAYABLE AMOUNT', rupees(payslip.netPay)]],
    headStyles: { fillColor: [5, 150, 105], textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9, cellPadding: 3 },
    footStyles: {
      fillColor: [240, 253, 244],
      textColor: [6, 95, 70],
      fontStyle: 'bold',
      fontSize: 10,
      cellPadding: 4,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 14, right: 14 },
    tableWidth: 'wrap',
  })

  // Net pay highlight box
  const netY = doc.lastAutoTable.finalY + 10
  doc.setFillColor(240, 253, 244)
  doc.roundedRect(14, netY, pageW - 28, 18, 3, 3, 'F')
  doc.setDrawColor(167, 243, 208)
  doc.roundedRect(14, netY, pageW - 28, 18, 3, 3, 'S')

  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(6, 95, 70)
  doc.text('NET SALARY CREDITED', 20, netY + 7)
  doc.setFontSize(14)
  doc.text(rupees(payslip.netPay), pageW - 20, netY + 8, { align: 'right' })
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(16, 185, 129)
  doc.text('After PF and ESI deductions', 20, netY + 14)

  // Footer note
  const footY = netY + 28
  doc.setFontSize(7)
  doc.setTextColor(150, 150, 150)
  doc.text(
    'This is a computer generated payslip and does not require a signature.',
    pageW / 2, footY, { align: 'center' }
  )
  doc.text(
    'PF = 12% of gross  |  ESI = 0.75% of gross  |  Overtime rate = 1.5x  |  Generated by PayStride',
    pageW / 2, footY + 5, { align: 'center' }
  )

  doc.save(`PayStride_Payslip_${workerCode}_${payslip.monthYear}.pdf`)
}
